config/routes.rb
Rails.application.routes.draw do

  resources :links
  post 'links/:id/upvote' => 'links#upvote', as: 'upvote'
  post 'links/:id/downvote' => 'links#downvote', as: 'downvote'
  root 'links#index'
end

app/models/category.rb
class Category < ActiveRecord::Base
  has_many :links
end

app/models/link.rb
class Link < ActiveRecord::Base
  belongs_to :category

  def upvote
    self.votes += 1
  end

  def downvote
    self.votes -= 1
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
end

app/controllers/links_controller.rb
class LinksController < ApplicationController
  respond_to :html, :json

  def index
    @links = Link.all.order(votes: :desc)
    @link = Link.new
  end

  def new
    @link = Link.new
  end

  def create
    @link = Link.new(link_params)
    @link.votes = 0
    if @link.save
      redirect_to root_url
    end
  end

  def upvote
    @link = Link.find params[:id]
    @link.upvote
    @link.save

    respond_to do |format|
      format.js
    end
  end

  def downvote
    @link = Link.find params[:id]
    @link.downvote
    @link.save

    respond_to do |format|
      format.js
    end
  end

  private

    def link_params
      params.require(:link).permit(:name, :url)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/links_helper.rb
module LinksHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Upvote</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
	<div class="container">
		<%= yield %>
	</div>
</body>
</html>

app/views/links/downvote.js.erb
$(".link-<%= @link.id %>").html("<%= @link.votes %>");

app/views/links/index.html.erb
<%= render 'shared/navigation' %>

<div class="feed-container">
  <ul class="feed">
    <% @links.each do |link| %>
      <li class="feed-item">
        <div class="votes-mod">
          <%= button_to '', upvote_path(link), remote: true, class: 'btn-upvote' %>
          <div class="link-<%=link.id%>"><%= link.votes %></div>
          <%= button_to '', downvote_path(link), remote: true, class: 'btn-downvote' %>
        </div>
        <div class="link-content">
          <p><%= link_to link.name, link.url, class: 'link-url' %></p>
        </div>
      </li>
    <% end %>
  </ul>
</div>

<div class="form-container">
  <div class="btn-new">
    <a href="#">
      <p>+ New</p>
    </a>
  </div>
  <div class="link-form-container">
    <%= form_for @link do |f| %>
      <%= f.text_field :name %><br />
      <%= f.text_field :url %><br />
      <%= f.submit %>
    <% end %>
  </div>
</div>

app/views/links/upvote.js.erb
$(".link-<%= @link.id %>").html("<%= @link.votes %>");

app/views/shared/_navigation.html.erb
<div class="navigation-container">
	<h1><a href="/" class="logo">upvote</a></h1>
</div>